project:
  type: website

website:

  # overall options
  title: "M.H.K. Hesselbarth"
  site-url: "https://www.maxhesselbarth.com"
  
  # general options
  search: true
  favicon: "images/icon.png"
  
  # github links
  repo-url: https://github.com/mhesselbarth/homepage/
  repo-actions: [issue]
  
  # twitter links
  twitter-card:
    creator: "@MHKHesselbarth"
  
  # navigation bar
  navbar:
    logo: "images/icon.png"
    left:
      - href: publications.html
        text: Publications
      - href: presentations.html
        text: Presentations
      - href: software.html
        text: Software
      - href: cv.html
        text: CV
      - href: contact.html
        text: Contact
        
  # page footer
  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; 2026 M.H.K. Hesselbarth, {{< fa brands creative-commons >}} [BY 4.0](https://creativecommons.org/licenses/by/4.0/)"

# format 
format:
  html:
    theme: [cosmo, custom.scss]
    toc: false
    page-layout: full
